### ISSUE TITLE
422 - persona credential exists

### ISSUE THREAD

**Issue by bsclifton** [brave-intl/bat-client#18]
Per https://github.com/brave/browser-laptop/pull/11495#issuecomment-336361446
Ran into an issue while testing that PR...  Here's what I did:
- created branch new v1 wallet using Brave 0.18.x
- switch to the PR branch / rm node_modules / npm install / etc and pointed it at the 0.18.x session
- wallet upgrade shows as in progress 👍 
- I quit and relaunched a few times- I verified that `ledger-newstate.json` gets persisted before and after after sync 👍 
- I seem to be getting an error now, HTTP code 422

```
<<< POST https://ledger.mercury.basicattentiontoken.org/v2/registrar/persona/1ed2a2b0748089c8ccd81e7dac8c893
<<< content-type: application/json; charset=utf-8
<<< accept-encoding:
<<<
<<< {
<<<   "requestType": "httpSignature",
<<<   "request": {
<<<     "headers": {
<<<       "digest": "SHA-256=oe2fifEDcfI96boPcKaUUhe/HKWiuzyoBs10Gm+S4bg=",
<<<       "signature": "keyId=\"primary\",algorithm=\"ed25519\",headers=\"digest\",signature=\"vglrshpOIBjtoW6OBmW70pH7/RFK7vwzY+a3a9rDdwGxIU9VTBgj0Snm2AEHrqQUuR3mA+EX817oh/z/607FCg==\""
<<<     },
<<<     "body": {
<<<       "label": "4123099f-47e4-48ad-bc9f-6cdffebd81ed",
<<<       "currency": "BAT",
<<<       "publicKey": "429fb47298b7b058030c3d1bca1ca587585a81b1e47f0ecc9436e04306210043"
<<<     },
<<<     "octets": "{\"currency\":\"BAT\",\"label\":\"4123099f-47e4-48ad-bc9f-6cdffebd81ed\",\"publicKey\":\"429fb47298b7b058030c3d1bca1ca587585a81b1e47f0ecc9436e04306210043\"}"
<<<   },
<<<   "proof": "1ed2a2b0748089c8ccd81e7dac8c893\n7FxI5Yngr+RGK1uVGD9rWf/RMzpzMz2irqOoj6t9DOH 5xbHQ55+WSAbb5PjpJhKRGY/1u65rlE2BEXkt/HSBMe 1\n13D36D8a7pG56RdRGmI0NoNPY7AjP4YaYh+fTjIjFTv 8gwqQ7TkDtR9rJ6XNhQ6j5RpWY6CEbFKtCMPks4UmkM 1\n2YOcc2YrRugyGZOJrgDOGhBWwO/6+OsMCaJ0RbbjOx9\n5j3+EjAim1nxwiO7UbO8Gc17maim1QxYP5pMWTgUh2b 4WdiDvvTxgXwZc2xueVmFhnvAJ0CawmUaCDZ6Bsr5G5\n\n6PDzgyvawQBE+Ndu7yAV3XiGyV4gcnRKV74Q5QqQYvS 7i16apf3Fk4v3bdROu1fm9DEVrFRCFx0qhzY1woyJcB 1\nF5KSCVbKPt+9RXeAPt7WCaAwVjAeEf1UhxvsjhEYMTg\nBETV/Mnj5p0TjkQO6/MEbQrUPXdoRCXBfAH/fPDF+Ai 3UqevUsbtwxqNn9hVwaZeh13SlCYYDuaP9brmW9wz9n\n\n5wSFmTSkk3rgWr90uyHne1ZQ3c4xfsCuGMAPw0bHw56 4yIpZvGfdV+6pi0WMSZ55knoA1WJ0RK+dZdS2qXd01n 1\nEyxwGIpFJnew4/ltJlP9bmKSHIl/YOGai0VgBSxKVmm\n9cD1As+2yjj4+bgD56OlhDiRnihOvU4dgOtGskhfx8w 8RF3dVpPL0hSBfV1DM+VmDqNBBJw0qu0mDx2NvTFOcC\n\n3GdmB6jP/KLU/zk9ya2f0GO+O1rjkv/yiSKxDZm57XD 4P/fkCg3ka+pw0o+aByXOnx+CM9dkTNLi/nVVG6SHek 1\n3AmjLTzsgwrq7yy4VvobP6XC0YCINMGpdX+uEMEYcJ\nAjfAU8PaYhcZHNhBJtGUsnk1khsH1I9WS3mbYHmc3RK B1lMaDXW+LwBT7z4hK7QXarvMVO/7G4/uF482IAd0zA\n\n\n"
<<< }
[ response for POST https://ledger.mercury.basicattentiontoken.org/v2/registrar/persona/1ed2a2b0748089c8ccd81e7dac8c893 ]
>>> HTTP/1.1 422
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 120
>>> content-type: application/json; charset=utf-8
>>> date: Fri, 13 Oct 2017 06:02:22 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 59
>>> x-rate-limit-reset: 1507874601
>>>
>>> {"statusCode":422,"error":"Unprocessable Entity","message":"persona credential exists: 1ed2a2b0748089c8ccd81e7dac8c893"}
ledger client error(3): {}
Error: HTTP response 422 for POST /v2/registrar/persona/1ed2a2b0748089c8ccd81e7dac8c893
    at request.request (/Users/clifton/Documents/browser-laptop/app/browser/api/ledger.js:1491:9)
    at Function.defaultSession.webRequest.fetch (/Users/clifton/Documents/browser-laptop/js/lib/request.js:55:5)
```

**Comment by mrose17** [comment]
@evq - i think you know this best. if i'm wrong, please let me know.

**Comment by evq** [comment]
Found the root cause, opening a browser-laptop issue to track since the fix is there.
